AWSTemplateFormatVersion: 2010-09-09
Description: >
  Networking resources for Web Blog environment. 
  Contains 2 public and 2 private subnets in a VPC with IGW access. 
Resources:
    VPC:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: "10.0.0.0/16"
        EnableDnsHostnames: true
        EnableDnsSupport: true
        Tags:
          - Key: Name
            Value: !Join ['', [!Ref "AWS::StackName", "-VPC"]]
    PublicSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: "10.0.0.0/24"
        MapPublicIpOnLaunch: true
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: "Public Subnet AZ A"
        AvailabilityZone:
          Fn::Select:
            - "0"
            - Fn::GetAZs:
                Ref: "AWS::Region"
    PublicSubnet2:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: "10.0.1.0/24"
        MapPublicIpOnLaunch: true
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: "Public Subnet AZ B"
        AvailabilityZone:
          Fn::Select:
            - "1"
            - Fn::GetAZs:
                Ref: "AWS::Region"
    PrivateSubnet1:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: "10.0.10.0/24"
        MapPublicIpOnLaunch: false
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: "Private Subnet AZ A"
        AvailabilityZone:
          Fn::Select:
            - "0"
            - Fn::GetAZs:
                Ref: "AWS::Region"
    PrivateSubnet2:
      Type: "AWS::EC2::Subnet"
      Properties:
        CidrBlock: "10.0.11.0/24"
        MapPublicIpOnLaunch: false
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: "Private Subnet AZ B"
        AvailabilityZone:
          Fn::Select:
            - "1"
            - Fn::GetAZs:
                Ref: "AWS::Region"
    RouteTablePublic:
      Type: "AWS::EC2::RouteTable"
      Properties:
        VpcId:
          Ref: "VPC"
        Tags:
          - Key: "Name"
            Value: "Public Route Table"
    RouteTablePublicAssociation1:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        RouteTableId:
          Ref: "RouteTablePublic"
        SubnetId:
          Ref: "PublicSubnet1"
    RouteTablePublicAssociation2:
      Type: "AWS::EC2::SubnetRouteTableAssociation"
      Properties:
        RouteTableId:
          Ref: "RouteTablePublic"
        SubnetId:
          Ref: "PublicSubnet2"
    RouteTablePublicRoute0:
      Type: "AWS::EC2::Route"
      Properties:
        DestinationCidrBlock: "0.0.0.0/0"
        RouteTableId:
          Ref: "RouteTablePublic"
        GatewayId:
          Ref: "Igw"
    Igw:
      Type: "AWS::EC2::InternetGateway"
      Properties: {}
    IGWAttachment:
      Type: "AWS::EC2::VPCGatewayAttachment"
      Properties:
        VpcId:
          Ref: "VPC"
        InternetGatewayId:
          Ref: "Igw"
  
